# Generated by Django 2.2.18 on 2021-04-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Full-Stack Developer', 'Full-Stack Developer'), ('UX Designer', 'UX Designer'), ('Product Manager', 'Product Manager'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Staff member', 'Staff member')], default='Staff member', max_length=20),
        ),
    ]
