# Generated by Django 2.2.18 on 2021-04-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20210404_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('On hold', 'On hold')], default='Todo', max_length=11)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('labels', models.ManyToManyField(blank=True, to='activity.Label')),
                ('project_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='account.Staff')),
                ('staff_members', models.ManyToManyField(related_name='activity_project_related', to='account.Staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('On hold', 'On hold')], default='Todo', max_length=11)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('labels', models.ManyToManyField(blank=True, to='activity.Label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activity.Project')),
                ('staff_members', models.ManyToManyField(related_name='activity_task_related', to='account.Staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
