# Generated by Django 2.2.18 on 2021-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20210413_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
